name: Release to Production
on:
  release:
    types: [published]
jobs:
  release:
    # needs: test
    uses: ./.github/workflows/vercel_deploy.yml
    with:
      production: true
    secrets: inherit
